[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "pillow>=11.2.1",
    "pytesseract>=0.3.13",
    "python-telegram-bot==20.3",
]
